language: php
php:
- 7.0
- hhvm
env: 
matrix:
  exclude:
  - php: hhvm
    env: DB=pgsql
  allow_failures:
  - php: 7.0
  - php: hhvm
before_script:
- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;"
  -U postgres; fi
- if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres;
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;"
  -uroot; fi
script: phpunit --configuration phpunit_$DB.xml --coverage-text
notifications:
  irc: irc.freenode.org#yourfavouriteroomfortravis
deploy:
  provider: heroku
  api_key:
    secure: L8NrU5tmg2Zgl2u1295PEHLS3l08HgTBUy3moITxbghA5rGoBYYu+SHE/OAc2YW96tYEB2yBdZHSwTy6Tzd/GbcWkm6cGYIheNQEDo5cCAf+J7jCOPPPk3/li7qaK4/XmPxnSvYkBrp68DVRIxDxj8BDJGqloUCqrBAg/AWrQkmpIwGGGD9PEp4fF+hpqoal48o6pJByaneOGHYS14H4eYU7EDhvWRGYwMj0j4/dAkZkkrCKZGqCpwujT407QM3Q7oNAn4xMCsMrpFwcgOsg6PQ1udPlh+yTsZJ0MsHsxY4ewy6Ok7lA5N+aaHSYpltLPyWzo+wg6sohmgzo8NdxOU6H+um0kWS/8Jsm7agPZHezRKOlRz0ki3LRhF0kzHX6c0k2CtOUZoB5yRbtk0BDO2tncdVtqAnJ8V29o1V1wKBCfB+pmJ/KHXcD1xmtIfracJ59DvuKMJ8B5BtwjN2aUJ81U2wgrKFiDR3guGU32ZVnxeT7cMZcAM+q9PB8Yjr7ntNNT9YdDFM6n2i0ctRd3U+t7r9E9KhaqVt+tp3D3MVslO1/383LGs5Ue5xYmrqDKyrJMJg6qLmQLzEykUPro/LHk8KYEkNdFMA30WAQtGZbqJ8RztA3WPZgJuqPM6BGtzlHWekk9IaNrd/izvq4B2UYtEoY0qbRwIghdHfreYs=
  app: mine-travis-test
  on:
    repo: giacomo-secchi/mine-travis-test
