language: php
php:
- 7.0
- hhvm
env: 
matrix:
  exclude:
  - php: hhvm
    env: DB=pgsql
  allow_failures:
  - php: 7.0
  - php: hhvm
before_script:
- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;"
  -U postgres; fi
- if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres;
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;"
  -uroot; fi
script: phpunit --configuration phpunit_$DB.xml --coverage-text
notifications:
  irc: irc.freenode.org#yourfavouriteroomfortravis
deploy:
  provider: heroku
  api_key:
    secure: zh/SXlnqYy96y1qvtqJzKiclbrErEtx78wc8AZyD1HyoFsj3rEul9GPRjyB2oyVc+OOTbdgOL/h4wCgphMDFqoseSzxEGh1HtifBhRg4iGHtlAoSQcTwq8LiCLSRMW6y2URLypss+caZjeMmhmkoU6skOE+TKPdzewaX9Z3pROCD6FFFI8Dc9CayUUwPUvAy3JAM7/AJ3lfzZE7pHlOo5TklHD+pSvjZyAfyrNwECuvXpHUM9v5GTkhU2xh3keGDLkYWEWSalIVRe9+fyIbqD/EqLp9kk/qv7Sj5VM/r5+QQ9RNB8Xle30lXobehyTS1dDzpiNDf0cxDPWOfqA6yr/F/I1jNZLzHhvvzFf3r06oeeXzjTWRvqanTnRU+ke0xe5QSGt55wxw/0lS6WmDeq8SjyYEjskCmfsdQXypprCgwMwJeqm89oydJCChjgbvqRLhsEc/ilnACnUFEvpzIAur92uUxTE71zojMrnVzWqZd+KZYm1rgCq4YDN7N5Z30OY0bsY1sjH66VjWvFYXfkj4eoytaB4eGVwTcw21psObtK7f33FgYEA4xxoT24puCHX6kprGFWDupt5VRLknm2MT4STg/BiMHjmhExWzeGRcNVxNrPZk2FDru5QnZh8QPb1w/XN+nAxII2dqCtIGdtLt/BXnjsneGppdsHARPqHQ=
  app: mine-travis-test
  on:
    repo: giacomo-secchi/mine-travis-test
