language: php
php:
- 7.0
- hhvm
env: 
matrix:
  exclude:
  - php: hhvm
    env: DB=pgsql
  allow_failures:
  - php: 7.0
  - php: hhvm
before_script:
- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;"
  -U postgres; fi
- if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres;
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;"
  -uroot; fi
script: phpunit --configuration phpunit_$DB.xml --coverage-text
notifications:
  irc: irc.freenode.org#yourfavouriteroomfortravis
deploy:
  provider: heroku
  api_key:
    secure: Gds76sQ54uhxRl3DjdUO61SmyyqqGrw/f5il07j7XQyfUEGe/t9ib7xTOjNsh0iL8LWj8S89o6McRMpRqOLv6qun8UdpoY1g3GQrBScnGKW8HiagjzcMBO26CXk9ftyebL6UALXCvZ7llElMVgaRLVm2P6nSozm3NqVCd4lNrxxBlGfrJ5hgLVU5N4pZ/6chEXqX2QylmucIFWH6JBszv+ycQOu3lrRTSy05KA+oM+K2VunyPM6z/avodyG++QhlxcVbv7cMoFSXEWY3GuhIbb5hy1qx4b62eiDa4MleSOzmv0F40f9BttzIYY+zQqDatKyBZUQHSR3dnko0lY4866836SfsxHIh7/7echW9avGVxDNjfIdzk9urnhMUKQlJnH+BGFHfY3xTsVuwW4IC+bVzh/Z6X7SLnuI8X3PZ5w8/C06xW7vYZKZW76wLEycbLLcLDn69/L0TRm9b0FwIvPBGFWeZ8Mw8sPi6GjaUCdaVO03aiHySnFeTNl4Oi3nuFE0RyZzDj3IlrRObbkPtty5Hv7AoLTZ/85pehus7MpfUUIAJtFB/v/j5sqQo3KliDVGU0CITQhxLjOF1l/19uhb5ZQ+16nz42w6yPncaHsuD7uqBjt/lybq3hA5w/kpyWcNARqAwkxAOBjT3fSimt39XMax/Pd+/HbfBQRgtM9U=
  app: mine-travis-test
  on:
    repo: giacomo-secchi/mine-travis-test
