language: node_js
node_js:
- 7
- 8
- 10
before_install:
- npm install -g npm
script:
- npm install
- npm run pretest
deploy:
  provider: heroku
  api_key:
    secure: $TEST
  app: mine-travis-test
  on:
    repo: giacomo-secchi/mine-travis-test
    all_branches: true
# env:
#   global:
#     secure: nu5mE46QXJ4V/O0ENiA9vUK56N0lNrRJoT114LNBFP38NOGcY9EgKIGSow1iSTuBZFHB6FbcBcdgFymbFiQVT0fZy8fqGYpdtprXmodESNLWPJZLsKNV2FKcRn5NziX8tWqEjo6bgiyjeliXhseXeNQXgwmIzfLo9zoP11ni0l0s0UQzUhHFeZX8a42aeChybYaRBp8mbkTu2fFKuX47Cei+vL0x3V2JRC4TztF1fo7yR+NqevVRKHZZo+VFzmA9gzf1z7vphuYSh4jIyPgwoZDXqoEdPml8kGyWVRLbUD2IRUuAn8eSCyM6FsNANRWaaxZoVBvuEYl2pPSdyp0awH2tQxIR9AYqqxX3b01W+P8ZDb1TM4YKumXVOPlit0/pwdKcCLGLKgS+WKoTCgHAdU/CEL328NMD0sejUDzA0OhLVY7LGqlELeddtL+OBMMkDi8XxnOOovxWGD1k8IMmrc8aqkiKiVWShSk90c9ZVXoSWzXxY6+kOAvdFnJqC2oHQ8+3qspOLJJxmuz95A093rDmxXkHnwNcpHhX0OhcYtBPAN/ZWiiuEVdxrQThPmHWDYOF33YQawJNOt/+leaO6HazKOueRqqYnylXedw7uVi6pcoEtu4Qe12hHSfzgHWcwVgk99r+yjUsVI0JOR2U0VpOpJO4O5OGX7DZPI0W3Uc=
    